configName: mzda_sk_extddr_meb2_tm4301b
folderName: mzda_sk_extddr_meb2_tm4301b
format_version: v1.0
frameworkPath: C:\Users\Mohit\Harmony3
processor: PIC32MZ2064DAA288
projectName: mzda_sk_extddr_meb2_tm4301b
settings:
  PackageFilter: bsp;bt;core;core_apps_pic32mz_da;core_apps_sam_e70_s70_v70_v71;crypto;cryptoauthlib;csp;gfx;gfx_apps;gfx_apps_pic32mz_da;gfx_aria;net;quick_docs;touch;usb;usb_apps_device;usb_apps_host;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAA288.atdf
