format_version: v1.0
type: UniqueComponent
attributes: {id: sys_input}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: MaxEvents}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '60'}
  - type: Integer
    attributes: {id: MaxListeners}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '478', y: '20', id: sys_input}
